### ISSUE TITLE
需要一个专门的 Usage 文档

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#13]
现在的 README 已经有些长了。写一个 USAGE.md 从 README.md 指向过去会更好。

**Comment by aisuneko** [comment]
我来做这个吧（
顺便写个英文 README

**Comment by cyjin-yl** [comment]
> 我来做这个吧（ 顺便写个英文 README

i18n 启动~~!

**Comment by cyjin-yl** [comment]
https://github.com/255doesnotexist/lintestor/commit/f79a6ac36375c7811e48cd951c4bfa090f83c8d8 初步草稿

**Comment by aisuneko** [comment]
Fixed with https://github.com/255doesnotexist/lintestor/commit/8381c435c032437278aa793138c4cbee97479151 :)
