### ISSUE TITLE
remote模式下无法正确获得测试脚本返回值

### ISSUE THREAD

**Issue by panglars** [255doesnotexist/lintestor#16]
我尝试使用remote(SSH)模式测试vf2在debian上的软件包,发现所有测试都能轻松通过

查看 remote.rs 在[这里](https://github.com/255doesnotexist/lintestor/blob/57aabdcd1af80536b8a3ab898351543784d78165/src/test_runner/remote.rs#L190C13-L190C46) is_ok 无法判断测试脚本返回值.
但其他其他命令也用了这个run_command,需要忽略他们的exit_status值

**Comment by cyjin-yl** [comment]
应该是最近几次 commit 更改导致的，我排查一下

**Comment by cyjin-yl** [comment]
https://github.com/255doesnotexist/lintestor/commit/b4d9884bb88c264ac88b1390e12efe8165298ab2 https://github.com/255doesnotexist/lintestor/commit/c1ff887fc625d52b9f7f5beab019d892d20bfb31 https://github.com/255doesnotexist/lintestor/commit/e3d386e1db24772d8c8328208c2b615d94ca0260 已修复。
