### ISSUE TITLE
Lintestor 在 CI 上因 Metadata 机制执行失败

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#20]
故障现场：https://github.com/255doesnotexist/lintestor/actions/runs/10986800026/job/30500686969

元数据 vec 没有收到足够的数据。

**Comment by aisuneko** [comment]
@255doesnotexist 你之前在板子上通过ssh测试没有遇到吗...? 我这边暂时没有能用于remote测试的环境

**Comment by cyjin-yl** [comment]
> @255doesnotexist 你之前在板子上通过ssh测试没有遇到吗...? 我这边暂时没有能用于remote测试的环境

我提交最后一次 commit 的时候还是能在 infra 上正常工作的... 后面的更改我没有看过。
也许 CI 上的运行环境有些不同。

**Comment by aisuneko** [comment]
Fixed with https://github.com/255doesnotexist/lintestor/commit/7020cd57a84ac2ed3e49aaf7ad3558401f34d837 (also added debug outputs for future use)
