### ISSUE TITLE
测试环境信息独立到表格下方

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#21]
测试环境信息在同一列都是完全相同的，单开一列过于冗余。

应当追加到表格下方，可通过（引用？链接？）形式跳转。

**Comment by aisuneko** [comment]
Draft implementation available: 6ffb21e3babc102508e2a371d382db022ff2ee2a 69d921dbe6505745f45ca507a59dc409e785af02 809328444a1f4c3f5b3febb5a38f6f7a18021e84
More enhancements to come, closing for now
