### ISSUE TITLE
一个命令行参数，可以指定单测某些包、或某些发行版。

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#24]
一个命令行参数，可以指定单测某些包、或某些发行版。

```shell
--参数名 "*/*" # 全部测试
--参数名 "*/gcc" # 所有发行版的 gcc 包
--参数名 "debian/*" # 重测所有 debian 的包
```

能支持正则匹配更是妙妙^^

参数名待定。

**Comment by aisuneko** [comment]
或者只重测上一次 `reports.json` 里失败的包
叫 `--retest` `--retest-all` `--retest-failed` 如何，还是有更好的名称...?

**Comment by cyjin-yl** [comment]
> 或者只重测上一次 `reports.json` 里失败的包 叫 `--retest` `--retest-all` `--retest-failed` 如何，还是有更好的名称...?

听你的^^

**Comment by aisuneko** [comment]
Draft implementation available at f78035383a71b031cc37de4eaa763882e524cf4e, with two new flags `--distro` and `--package`

- More error handling needed
- Need to rewrite the root_config parser to enable different package configs for different distros

**Comment by cyjin-yl** [comment]
> * Need to rewrite the root_config parser to enable different package configs for different distros

嗯... 为每个发行版提供不同的需要测试的包列表，合适吗？

```toml
distros = ["A", "B"]
packages = {
    "A": [...]
    "B": [...]
}
```

但是实际上大部分发行版需要测试的包列表是非常接近的。

**Comment by aisuneko** [comment]
> 
> ```toml
> distros = ["A", "B"]
> packages = {
>     "A": [...]
>     "B": [...]
> }
> ```

我想的是
```
[distro1]
packages = [...]

[distro2]
packages = [...]
```
但这个不是一个固定 struct 而是动态的，不清楚可以怎么parse

> 但是实际上大部分发行版需要测试的包列表是非常接近的。

虽然确实如此，目前的实现（因为有做缺少的包/发行版直接跳过的error handling）也不至于bug很多，但还是觉得共用同一个包列表有些不合逻辑...

**Comment by cyjin-yl** [comment]
> 虽然确实如此，目前的实现（因为有做缺少的包/发行版直接跳过的error handling）也不至于bug很多，但还是觉得共用同一个包列表有些不合逻辑...

当时这么设计的考量是基于最终产物：那个矩阵考虑的。用两个列表刚好分配给表格的行和列，表格里总得填上东西（空、失败、成功、异常什么的）。倒是没有考虑单测的情况。

**Comment by cyjin-yl** [comment]
> [distro1]
> packages = [...]
> 
> [distro2]
> packages = [...]

类似的结构用 toml 其实是可以写的。倒不算问题。

**Comment by aisuneko** [comment]
> > 虽然确实如此，目前的实现（因为有做缺少的包/发行版直接跳过的error handling）也不至于bug很多，但还是觉得共用同一个包列表有些不合逻辑...
> 
> 当时这么设计的考量是基于最终产物：那个矩阵考虑的。用两个列表刚好分配给表格的行和列，表格里总得填上东西（空、失败、成功、异常什么的）。倒是没有考虑单测的情况。

problem solved with acf634fd2c59859ca5cf3fc31cc3e63256258526 (simply got rid of root configs)
