### ISSUE TITLE
一个命令行参数，可以跳过对已经有结果的包的测试。

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#25]
一个命令行参数，可以跳过对已经有结果的包的测试。

参数名待定。

**Comment by aisuneko** [comment]
那就跟现有的 `--cleanup` 参数合并好了：相当于选择是否覆盖已有测试
默认行为是覆盖还是不覆盖？
以及叫 `--skip-tested` 如何? (这名字感觉怪怪的)

**Comment by cyjin-yl** [comment]
> 那就跟现有的 `--cleanup` 参数合并好了：相当于选择是否覆盖已有测试 默认行为是覆盖还是不覆盖？ 以及叫 `--skip-tested` 如何? (这名字感觉怪怪的)

`--skip-tested` 感觉像什么中式英语，和 report.json 里的 `all_tests_passed` 映照成~~别出心裁~~的离调音。

但你问我资瓷还是不资瓷，那我当然是资瓷的。 

同意！

**Comment by aisuneko** [comment]
> `--skip-tested` 感觉像什么中式英语

~~被骂了（不是）~~
好吧这个我再想想... 所以默认行为应该是覆盖还是不覆盖已有测试来着

**Comment by aisuneko** [comment]
Draft implementation available at f91085286b731514facb629cf33c189458ae0a9f 4f115a7bc9607ae29391ca3e21f6ae9c459f3e34

**Comment by cyjin-yl** [comment]
> Draft implementation available at [f910852](https://github.com/255doesnotexist/lintestor/commit/f91085286b731514facb629cf33c189458ae0a9f) [4f115a7](https://github.com/255doesnotexist/lintestor/commit/4f115a7bc9607ae29391ca3e21f6ae9c459f3e34)

酷酷
