### ISSUE TITLE
每周自动测试的 Action 执行后自动同步到仓库中 

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#7]
每周 lintestor 自动测试结束后，变更的 summary.md 和 reports.json 自动 commit 并 push 到本仓库中。

**Comment by aisuneko** [comment]
是否应该另开一个分支存放这些artifact? （以免跟开发分支混在一起）
而且 Actions 的机器只是一个qemu, 感觉如果能有一个实体板子 infra 的话再部署这个会更实际一点

**Comment by cyjin-yl** [comment]
> 是否应该另开一个分支存放这些artifact? （以免跟开发分支混在一起） 而且 Actions 的机器只是一个qemu, 感觉如果能有一个实体板子 infra 的话再部署这个会更实际一点

我支持

**Comment by cyjin-yl** [comment]
已经在 Oct. 15 的提交 https://github.com/255doesnotexist/lintestor/commit/6df46d3104407cb1afaa67cf00fa85decf554b95 中实现。
