### ISSUE TITLE
更详细的代码、注解文档补全

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#9]
更详细的代码、注解文档补全，至少别 docs 点进去一片白白的啥也没有 XD。

**Comment by cyjin-yl** [comment]
[testscript_manager](https://github.com/255doesnotexist/lintestor/commit/56d16264c1aef0d7d46e0328aa8224b339605b46) 的补了一点，但不多 XD。

**Comment by cyjin-yl** [comment]
@aisuneko: https://github.com/255doesnotexist/lintestor/commit/44f005cf33763cd920ee7f31ad86d04213ad0614 https://github.com/255doesnotexist/lintestor/commit/5d7fb9f1f998a0eb6c6f320e389251c4fcf68082
_: https://github.com/255doesnotexist/lintestor/commit/53c93e71f2e539b42477ab73a991184e62126e0c https://github.com/255doesnotexist/lintestor/commit/4f18892c95ad6ac275f0b03194ab41d3d636fc03

nearly finished

**Comment by aisuneko** [comment]
@255doesnotexist 我觉得这个issue其实可以close了（
因为现在基本都是每实现一个新特性/较大改动就会顺带维护对应的文档

**Comment by cyjin-yl** [comment]
> @255doesnotexist 我觉得这个issue其实可以close了（ 因为现在基本都是每实现一个新特性/较大改动就会顺带维护对应的文档

好喔。

**Comment by aisuneko** [comment]
@255doesnotexist 倒是说起来，考虑在CI里加入 doc/code coverage 吗？

**Comment by cyjin-yl** [comment]
> @255doesnotexist 倒是说起来，考虑在CI里加入 doc/code coverage 吗？

您说的对，加吧——
